env: "gymma"

env_args:
  key: null
  time_limit: 100
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 160000
log_interval: 160000
runner_log_interval: 160000
learner_log_interval: 160000
save_model_interval: 160000
t_max: 6600000
